service:
  name: serverless-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  getUser:
    handler: src/users/users.getUser
    description: Returns a single user.

    environment:
      DEFAULT_COUNTRY: N. Virginia

    events:
      - http:
          path: users/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
          documentation:
            summary: Get a user.
            tags:
              - User
            description: Returns the specified user.
            pathParams:
              - name: id
                description: The unique identifier of the user to retrieve.
            methodResponses:
              - statusCode: '200'
                description: Returned when the operation is completed successfully.
                responseModels:
                  "application/json": GetUserResponse   